### ISSUE TITLE
DB dumps seem to be in the repository

### ISSUE THREAD

**Issue by wd15** [usnistgov/corr#81]
Getting
```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File corr-db/data/corr-production.0 is 64.00 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File corr-db/data/local.0 is 64.00 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
To git@github.com:wd15/corr-cmd.git
```
when committing files. We shouldn't be adding database dumps to the repo. We can use a tool called BFG to rework the repository so those files are no longer part of it.

**Comment by faical-yannick-congo** [comment]
The data dump was taken out of the repo a long time ago. I don't have anything but zero.json in data in any of my branches and it is not either in master or develop in upstream. Also it is excluded in the gitignore. So i don't understand why you have that at all. And the data folder corr-db is in corr-db/corrdb/data not corr-db/data. I think you created a new data folder somewhere else. That is not out of version control.

**Comment by wd15** [comment]
@faical-yannick-congo, remember that we can rework the repositories to remove big files from the history altogether. However, right now I'm getting CoRR at 60M and CoRR-cli at 14M which is not huge so we can worry about it if they get above 100M.

**Comment by faical-yannick-congo** [comment]
Oh@ Now i understand. It is somewhere in the history at some point. Ok. Let's work on that next week if you don't mind. 
Thanks
